### ISSUE TITLE
Including this in my own VS project

### ISSUE THREAD

**Issue by FocuzJS** [chronoxor/CppServer#11]
I'm trying to integrate a websocket server into an existing visual studio project. I've managed to build this from source and get a .lib but I'm not too sure how straightforward including the necessary headers into my project is.. Sorry I'm fairly new to building c++ dependencies outside of VS.

**Comment by chronoxor** [comment]
The best way is to generate VS solution & projects files using CMake (-G "Visual Studio 16 2019") and add them to your existing project. This will add all necessary include directories, libs dependency in a proper way.

**Comment by Macfly** [comment]
could you explain how you did it? Because I have tried that but I get lots of compilation errors.

**Comment by FocuzJS** [comment]
I didn't.

**Comment by mirjalal** [comment]
After working on it for 6-7 days I did it & successfully added to my own project without any problem.
