### ISSUE TITLE
Does not compile in a bunch of Visual Studio and Debian 10

### ISSUE THREAD

**Issue by MuravyevArtem** [chronoxor/CppServer#16]
Hello! I am trying to compile an example of TCP chat server from Visual Studio in connection to Debian 10. But when compiling on the Linux side, I get the following errors:

1>/usr/bin/ld : error : /home/nollin/projects/MAIN_SERVER_CLASSIC_LINUX/obj/x64/Release/ServerHandler.o: in function `void __gnu_cxx::new_allocator<CppServer::Asio::Service>::construct<CppServer::Asio::Service>(CppServer::Asio::Service*)':
1>/usr/include/c++/8/bits/shared_ptr_base.h(541): error : undefined reference to `CppServer::Asio::Service::Service(int, bool)'
1>/usr/bin/ld : error : /home/nollin/projects/MAIN_SERVER_CLASSIC_LINUX/obj/x64/Release/ServerHandler.o: in function `CTCPServer::TCPServer(std::shared_ptr<CppServer::Asio::Service> const&, int, CppServer::Asio::InternetProtocol)':
1>D:\MainFiles\desctop\BlockadeClassic\MAIN_SERVER_CLASSIC_LINUX\ServerHandler.h(45): error : undefined reference to `CppServer::Asio::TCPServer::TCPServer(std::shared_ptr<CppServer::Asio::Service> const&, int, CppServer::Asio::InternetProtocol)'
1>/usr/bin/ld : error : /home/nollin/projects/MAIN_SERVER_CLASSIC_LINUX/obj/x64/Release/ServerHandler.o: in function `CppServer::Asio::TCPSession::Disconnect()':
1>/usr/include/CppServer/include/server/asio/tcp_session.h(75): error : undefined reference to `CppServer::Asio::TCPSession::Disconnect(bool)'
1>/usr/bin/ld : error : /home/nollin/projects/MAIN_SERVER_CLASSIC_LINUX/obj/x64/Release/ServerHandler.o: in function `CTCPSession::TCPSession(std::shared_ptr<CppServer::Asio::TCPServer> const&)':
1>D:\MainFiles\desctop\BlockadeClassic\MAIN_SERVER_CLASSIC_LINUX\ServerHandler.h(9): error : undefined reference to `CppServer::Asio::TCPSession::TCPSession(std::shared_ptr<CppServer::Asio::TCPServer> const&)'
1>/usr/bin/ld : error : /home/nollin/projects/MAIN_SERVER_CLASSIC_LINUX/obj/x64/Release/ServerHandler.o: in function `CppServer::Asio::Service::~Service()':
1>/usr/include/CppServer/include/server/asio/service.h(70): error : undefined reference to `vtable for CppServer::Asio::Service'
1>/usr/bin/ld : error : /home/nollin/projects/MAIN_SERVER_CLASSIC_LINUX/obj/x64/Release/ServerHandler.o: in function `CppCommon::operator<<(std::ostream&, CppCommon::UUID const&)':
1>/usr/include/CppCommon/include/system/uuid.h(97): error : undefined reference to `CppCommon::UUID::string[abi:cxx11]() const'
1>/usr/bin/ld : error : /usr/include/CppCommon/include/system/uuid.h:97: undefined reference to `CppCommon::UUID::string[abi:cxx11]() const'
1>/usr/bin/ld : error : /home/nollin/projects/MAIN_SERVER_CLASSIC_LINUX/obj/x64/Release/ServerHandler.o: in function `CppServer::Asio::TCPSession::~TCPSession()':
1>/usr/include/CppServer/include/server/asio/tcp_session.h(39): error : undefined reference to `vtable for CppServer::Asio::TCPSession'
1>/usr/bin/ld : error : /home/nollin/projects/MAIN_SERVER_CLASSIC_LINUX/obj/x64/Release/ServerHandler.o: in function `asio::detail::io_object_impl<asio::detail::reactive_socket_service<asio::ip::tcp>, asio::executor>::~io_object_impl()':
1>/usr/include/asio/asio/include/asio/detail/io_object_impl.hpp(116): error : undefined reference to `asio::detail::reactive_socket_service_base::destroy(asio::detail::reactive_socket_service_base::base_implementation_type&)'
1>/usr/bin/ld : error : /home/nollin/projects/MAIN_SERVER_CLASSIC_LINUX/obj/x64/Release/ServerHandler.o: in function `CppServer::Asio::TCPSession::~TCPSession()':
1>/usr/include/CppServer/include/server/asio/tcp_session.h(39): error : undefined reference to `vtable for CppServer::Asio::TCPSession'
1>/usr/bin/ld : error : /home/nollin/projects/MAIN_SERVER_CLASSIC_LINUX/obj/x64/Release/ServerHandler.o: in function `asio::detail::io_object_impl<asio::detail::reactive_socket_service<asio::ip::tcp>, asio::executor>::~io_object_impl()':
1>/usr/include/asio/asio/include/asio/detail/io_object_impl.hpp(116): error : undefined reference to `asio::detail::reactive_socket_service_base::destroy(asio::detail::reactive_socket_service_base::base_implementation_type&)'
1>/usr/bin/ld : error : /home/nollin/projects/MAIN_SERVER_CLASSIC_LINUX/obj/x64/Release/ServerHandler.o: in function `CppServer::Asio::Service::~Service()':
1>/usr/include/CppServer/include/server/asio/service.h(70): error : undefined reference to `vtable for CppServer::Asio::Service'
1>/usr/bin/ld : error : /home/nollin/projects/MAIN_SERVER_CLASSIC_LINUX/obj/x64/Release/ServerHandler.o: in function `CppServer::Asio::TCPServer::~TCPServer()':
1>/usr/include/CppServer/include/server/asio/tcp_server.h(57): error : undefined reference to `vtable for CppServer::Asio::TCPServer'
1>/usr/bin/ld : error : /home/nollin/projects/MAIN_SERVER_CLASSIC_LINUX/obj/x64/Release/ServerHandler.o: in function `asio::detail::io_object_impl<asio::detail::reactive_socket_service<asio::ip::tcp>, asio::executor>::~io_object_impl()':
1>/usr/include/asio/asio/include/asio/detail/io_object_impl.hpp(116): error : undefined reference to `asio::detail::reactive_socket_service_base::destroy(asio::detail::reactive_socket_service_base::base_implementation_type&)'
1>/usr/bin/ld : error : /home/nollin/projects/MAIN_SERVER_CLASSIC_LINUX/obj/x64/Release/ServerHandler.o: in function `CppServer::Asio::TCPServer::~TCPServer()':
1>/usr/include/CppServer/include/server/asio/tcp_server.h(57): error : undefined reference to `vtable for CppServer::Asio::TCPServer'
1>/usr/bin/ld : error : /home/nollin/projects/MAIN_SERVER_CLASSIC_LINUX/obj/x64/Release/ServerHandler.o: in function `asio::detail::io_object_impl<asio::detail::reactive_socket_service<asio::ip::tcp>, asio::executor>::~io_object_impl()':
1>/usr/include/asio/asio/include/asio/detail/io_object_impl.hpp(116): error : undefined reference to `asio::detail::reactive_socket_service_base::destroy(asio::detail::reactive_socket_service_base::base_implementation_type&)'
1>/usr/bin/ld : error : /home/nollin/projects/MAIN_SERVER_CLASSIC_LINUX/obj/x64/Release/ServerHandler.o: in function `CppServer::Asio::Service::~Service()':
1>/usr/include/CppServer/include/server/asio/service.h(70): error : undefined reference to `vtable for CppServer::Asio::Service'
1>/usr/bin/ld : error : /home/nollin/projects/MAIN_SERVER_CLASSIC_LINUX/obj/x64/Release/ServerHandler.o: in function `asio::error::get_system_category()':
1>/usr/include/asio/asio/include/asio/error.hpp(228): error : undefined reference to `asio::system_category()'
1>/usr/bin/ld : error : /home/nollin/projects/MAIN_SERVER_CLASSIC_LINUX/obj/x64/Release/ServerHandler.o: in function `__static_initialization_and_destruction_0':
1>/usr/include/asio/asio/include/asio/error.hpp(261): error : undefined reference to `asio::error::get_netdb_category()'
1>/usr/bin/ld : error : /usr/include/asio/asio/include/asio/error.hpp:264: undefined reference to `asio::error::get_addrinfo_category()'
1>/usr/bin/ld : error : /usr/include/asio/asio/include/asio/error.hpp:267: undefined reference to `asio::error::get_misc_category()'
1>/usr/bin/ld : error : /home/nollin/projects/MAIN_SERVER_CLASSIC_LINUX/obj/x64/Release/ServerHandler.o: in function `__static_initialization_and_destruction_0':
1>/usr/include/asio/asio/include/asio/ssl/error.hpp(37): error : undefined reference to `asio::error::get_ssl_category()'
1>/usr/bin/ld : error : /usr/include/asio/asio/include/asio/ssl/error.hpp:74: undefined reference to `asio::ssl::error::get_stream_category()'
1>/usr/bin/ld : error : /home/nollin/projects/MAIN_SERVER_CLASSIC_LINUX/obj/x64/Release/ServerHandler.o:(.data.rel.ro._ZTI11CTCPSession[_ZTI11CTCPSession]+0x10): undefined reference to `typeinfo for CppServer::Asio::TCPSession'
1>/usr/bin/ld : error : /home/nollin/projects/MAIN_SERVER_CLASSIC_LINUX/obj/x64/Release/ServerHandler.o:(.data.rel.ro._ZTI10CTCPServer[_ZTI10CTCPServer]+0x10): undefined reference to `typeinfo for CppServer::Asio::TCPServer'
1>/usr/bin/ld : error : /home/nollin/projects/MAIN_SERVER_CLASSIC_LINUX/obj/x64/Release/ServerHandler.o:(.data.rel.ro._ZTV11CTCPSession[_ZTV11CTCPSession]+0x28): undefined reference to `CppServer::Asio::TCPSession::Send(void const*, unsigned long)'
1>/usr/bin/ld : error : /home/nollin/projects/MAIN_SERVER_CLASSIC_LINUX/obj/x64/Release/ServerHandler.o:(.data.rel.ro._ZTV11CTCPSession[_ZTV11CTCPSession]+0x38): undefined reference to `CppServer::Asio::TCPSession::Send(void const*, unsigned long, CppCommon::Timespan const&)'
1>/usr/bin/ld : error : /home/nollin/projects/MAIN_SERVER_CLASSIC_LINUX/obj/x64/Release/ServerHandler.o:(.data.rel.ro._ZTV11CTCPSession[_ZTV11CTCPSession]+0x48): undefined reference to `CppServer::Asio::TCPSession::SendAsync(void const*, unsigned long)'
1>/usr/bin/ld : error : /home/nollin/projects/MAIN_SERVER_CLASSIC_LINUX/obj/x64/Release/ServerHandler.o:(.data.rel.ro._ZTV11CTCPSession[_ZTV11CTCPSession]+0x58): undefined reference to `CppServer::Asio::TCPSession::Receive(void*, unsigned long)'
1>/usr/bin/ld : error : /home/nollin/projects/MAIN_SERVER_CLASSIC_LINUX/obj/x64/Release/ServerHandler.o:(.data.rel.ro._ZTV11CTCPSession[_ZTV11CTCPSession]+0x60): undefined reference to `CppServer::Asio::TCPSession::Receive[abi:cxx11](unsigned long)'
1>/usr/bin/ld : error : /home/nollin/projects/MAIN_SERVER_CLASSIC_LINUX/obj/x64/Release/ServerHandler.o:(.data.rel.ro._ZTV11CTCPSession[_ZTV11CTCPSession]+0x68): undefined reference to `CppServer::Asio::TCPSession::Receive(void*, unsigned long, CppCommon::Timespan const&)'
1>/usr/bin/ld : error : /home/nollin/projects/MAIN_SERVER_CLASSIC_LINUX/obj/x64/Release/ServerHandler.o:(.data.rel.ro._ZTV11CTCPSession[_ZTV11CTCPSession]+0x70): undefined reference to `CppServer::Asio::TCPSession::Receive[abi:cxx11](unsigned long, CppCommon::Timespan const&)'
1>/usr/bin/ld : error : /home/nollin/projects/MAIN_SERVER_CLASSIC_LINUX/obj/x64/Release/ServerHandler.o:(.data.rel.ro._ZTV11CTCPSession[_ZTV11CTCPSession]+0x78): undefined reference to `CppServer::Asio::TCPSession::ReceiveAsync()'
1>/usr/bin/ld : error : /home/nollin/projects/MAIN_SERVER_CLASSIC_LINUX/obj/x64/Release/ServerHandler.o:(.data.rel.ro._ZTV10CTCPServer[_ZTV10CTCPServer]+0x20): undefined reference to `CppServer::Asio::TCPServer::Start()'
1>/usr/bin/ld : error : /home/nollin/projects/MAIN_SERVER_CLASSIC_LINUX/obj/x64/Release/ServerHandler.o:(.data.rel.ro._ZTV10CTCPServer[_ZTV10CTCPServer]+0x28): undefined reference to `CppServer::Asio::TCPServer::Stop()'
1>/usr/bin/ld : error : /home/nollin/projects/MAIN_SERVER_CLASSIC_LINUX/obj/x64/Release/ServerHandler.o:(.data.rel.ro._ZTV10CTCPServer[_ZTV10CTCPServer]+0x30): undefined reference to `CppServer::Asio::TCPServer::Restart()'
1>/usr/bin/ld : error : /home/nollin/projects/MAIN_SERVER_CLASSIC_LINUX/obj/x64/Release/ServerHandler.o:(.data.rel.ro._ZTV10CTCPServer[_ZTV10CTCPServer]+0x38): undefined reference to `CppServer::Asio::TCPServer::Multicast(void const*, unsigned long)'
1>/usr/bin/ld : error : /home/nollin/projects/MAIN_SERVER_CLASSIC_LINUX/obj/x64/Release/ServerHandler.o:(.data.rel.ro._ZTV10CTCPServer[_ZTV10CTCPServer]+0x48): undefined reference to `CppServer::Asio::TCPServer::DisconnectAll()'

What could be wrong with Asio?
Sorry if I asked stupidity - after several days of trying to compile, my head is already cloudy.

**Comment by MuravyevArtem** [comment]
Еще раз здравствуйте! Попытался скомпилировать код из раздела Example: Asio service в VisualStudio 2019. Создал пустой проект, создал файл Test.cpp и скопировал в него код из раздела Example: Asio service. Также настроил все пути к требуемым каталогам CppServer, CppCommon и Asio (взят с сайта https://think-async.com/Asio/). При попытке компиляции выдает такой результат: 

`1>------ Сборка начата: проект: Project1, Конфигурация: Release x64 ------
1>Test.cpp
1>Please define _WIN32_WINNT or _WIN32_WINDOWS appropriately. For example:
1>- add -D_WIN32_WINNT=0x0501 to the compiler command line; or
1>- add _WIN32_WINNT=0x0501 to your project's Preprocessor Definitions.
1>Assuming _WIN32_WINNT=0x0501 (i.e. Windows XP target).
1>Test.obj : error LNK2001: неразрешенный внешний символ ""void __cdecl asio::asio_handler_deallocate(void *,unsigned __int64,...)" (?asio_handler_deallocate@asio@@YAXPEAX_KZZ)"
1>Test.obj : error LNK2001: неразрешенный внешний символ ""class std::error_category const & __cdecl asio::system_category(void)" (?system_category@asio@@YAAEBVerror_category@std@@XZ)"
1>Test.obj : error LNK2001: неразрешенный внешний символ ""class std::error_category const & __cdecl asio::ssl::error::get_stream_category(void)" (?get_stream_category@error@ssl@asio@@YAAEBVerror_category@std@@XZ)"
1>Test.obj : error LNK2001: неразрешенный внешний символ ""void * __cdecl asio::asio_handler_allocate(unsigned __int64,...)" (?asio_handler_allocate@asio@@YAPEAX_KZZ)"
1>Test.obj : error LNK2001: неразрешенный внешний символ ""protected: static void __cdecl asio::detail::winsock_init_base::throw_on_error(struct asio::detail::winsock_init_base::data &)" (?throw_on_error@winsock_init_base@detail@asio@@KAXAEAUdata@123@@Z)"
1>Test.obj : error LNK2001: неразрешенный внешний символ ""protected: static void __cdecl asio::detail::winsock_init_base::cleanup(struct asio::detail::winsock_init_base::data &)" (?cleanup@winsock_init_base@detail@asio@@KAXAEAUdata@123@@Z)"
1>Test.obj : error LNK2001: неразрешенный внешний символ ""protected: static void __cdecl asio::detail::winsock_init_base::startup(struct asio::detail::winsock_init_base::data &,unsigned char,unsigned char)" (?startup@winsock_init_base@detail@asio@@KAXAEAUdata@123@EE@Z)"
1>Test.obj : error LNK2001: неразрешенный внешний символ ""unsigned long __cdecl asio::detail::win_tss_ptr_create(void)" (?win_tss_ptr_create@detail@asio@@YAKXZ)"
1>Test.obj : error LNK2001: неразрешенный внешний символ ""private: void __cdecl asio::detail::strand_service::do_post(class asio::detail::strand_service::strand_impl * &,class asio::detail::win_iocp_operation *,bool)" (?do_post@strand_service@detail@asio@@AEAAXAEAPEAVstrand_impl@123@PEAVwin_iocp_operation@23@_N@Z)"
1>Test.obj : error LNK2001: неразрешенный внешний символ ""private: bool __cdecl asio::detail::strand_service::do_dispatch(class asio::detail::strand_service::strand_impl * &,class asio::detail::win_iocp_operation *)" (?do_dispatch@strand_service@detail@asio@@AEAA_NAEAPEAVstrand_impl@123@PEAVwin_iocp_operation@23@@Z)"
1>Test.obj : error LNK2001: неразрешенный внешний символ ""public: void __cdecl asio::detail::win_iocp_io_context::post_deferred_completion(class asio::detail::win_iocp_operation *)" (?post_deferred_completion@win_iocp_io_context@detail@asio@@QEAAXPEAVwin_iocp_operation@23@@Z)"
1>Test.obj : error LNK2001: неразрешенный внешний символ ""class std::error_category const & __cdecl asio::error::get_ssl_category(void)" (?get_ssl_category@error@asio@@YAAEBVerror_category@std@@XZ)"
1>Test.obj : error LNK2001: неразрешенный внешний символ ""class std::error_category const & __cdecl asio::error::get_misc_category(void)" (?get_misc_category@error@asio@@YAAEBVerror_category@std@@XZ)"
1>Test.obj : error LNK2001: неразрешенный внешний символ ""public: __cdecl CppServer::Asio::Service::Service(int,bool)" (??0Service@Asio@CppServer@@QEAA@H_N@Z)"
1>Test.obj : error LNK2001: неразрешенный внешний символ ""public: static void __cdecl CppCommon::Thread::SleepFor(class CppCommon::Timespan const &)" (?SleepFor@Thread@CppCommon@@SAXAEBVTimespan@2@@Z)"
1>Test.obj : error LNK2001: неразрешенный внешний символ ""public: static unsigned __int64 __cdecl CppCommon::Thread::CurrentThreadId(void)" (?CurrentThreadId@Thread@CppCommon@@SA_KXZ)"
1>D:\MainFiles\desctop\BlockadeClassic\Project1\x64\Release\Project1.exe : fatal error LNK1120: неразрешенных внешних элементов: 16
1>Сборка проекта "Project1.vcxproj" завершена с ошибкой.
========== Сборка: успешно: 0, с ошибками: 1, без изменений: 0, пропущено: 0 ==========`

В чем может быть проблема?

**Comment by chronoxor** [comment]
Did you try to build CppServer following this instruction? 
https://github.com/chronoxor/CppServer#how-to-build

**Comment by MuravyevArtem** [comment]
У меня получилось собрать библиотеки cppserver.lib и cppcommon.lib. Я добавил их в зависимости проекта. Но при компиляции возникают те же самые ошибки asio. Я так понимаю, необходима еще и библиотека asio.lib. Но не понимаю как ее скомпилировать из исходников с сайта http://think-async.com/. В разделе http://think-async.com/Asio/asio-1.12.2/doc/asio/using.html есть пункт "Building the tests and examples with MSVC", но нет пункта, как собрать саму библиотеку. Извините, если спрашиваю глупости - у меня маловато опыта в сборке библиотек. В google полно руководств, как собрать библиотеки boost. Но на сколько я понял - boost.asio не работает с Вашей библиотекой cppserver.lib. Не могли бы Вы порекомендовать что нибудь для решения проблемы с asio?
