### ISSUE TITLE
What is the effort required to port it to c++11?

### ISSUE THREAD

**Issue by jaggukaka** [chronoxor/CppServer#17]
Hi I could successfully build and run the project and also could include in my own c++17 project, but I have some projects which can't be moved to c++17, I want to know  what is the effort required to port it to c++11? I see a lot of std::string_view references as a starter that needs modification, are there any other such c++17 specific apis used? simply put I just want to know if it is a huge effort, if it is what are the alternatives?
Thanks for the awesome work!

**Comment by chronoxor** [comment]
I think it won't be difficult. Just clone the repository and change `CppServer\cmake\SetCompilerFeatures.cmake` to:
```
# Choose C++ standard
set(CMAKE_CXX_STANDARD 11)
```

Then try to build it and fix minor compile issues such as std::string_view -> std::string, etc.

**Comment by jaggukaka** [comment]
Thanks, will try to do that!
