### ISSUE TITLE
performances

### ISSUE THREAD

**Issue by silviucpp** [chronoxor/CppServer#2]
Hello,

I just looked over your repo and it's pretty amazing. Congrats ! All interfaces looks pretty nice and self explanatory.

What I'm wonder it's the performance of this servers from a memory usage and requests/second they can serve point of view.

Looking to your results and on what machine you run the tests I see the HTTP/HTTPS server performances being very poor. Have you compared your results with other solutions ?

For example for websocket have you compared the HTTP and websocket performances with https://github.com/uNetworking/uWebSockets which seems a strong candidate ? 

Kind regards,
Silviu

**Comment by SoftFx** [comment]
Thanks for the link! I'll look into uWebSocksts as soon as possible. I have to say that both Restbed & WebSocksts++ have poore performance and are not recommended to be used in high load solutions.

**Comment by silviucpp** [comment]
I don't think should be too complicated to migrate the HTTP* and websocket implementation over uWebSocksts. The only challenge might be to patch their code to use an external loop (they already support asio)

**Comment by chronoxor** [comment]
I looked with one eye into uWebSockets. They already support Boost.ASIO loop. I have to provide a custom ASIO loop (without boost) and integrate uWebSockets with my CppServer and make examples & benchmarks. I'm going to do this in the next week. Hope we'll get very good performance results!

Concerning HTTP/HTTPS I'm not sure if uWebSockets provide necessary API to create REST service with user defined routing as Restbed does.

**Comment by silviucpp** [comment]
yes you are right needs some work to create a similar rest service in top of uWebSockets but shouldn't be so difficult as time the HTTP protocol is already implemented.

**Comment by chronoxor** [comment]
It seems that uWebSockets does not support Asio under Windows paltfrom - https://github.com/uNetworking/uWebSockets/pull/762
