### ISSUE TITLE
Custom compilation

### ISSUE THREAD

**Issue by nirajrussspacetech** [chronoxor/CppServer#20]
The unix.sh worked successfully and generated all examples in bin but How to compile customized udp_echo_server example ?
Please give details

**Comment by chronoxor** [comment]
Just put it's .cpp file into ./examples folder. It will be automatically discovered and built with output in ./bin

**Comment by nirajrussspacetech** [comment]
ok.. but I want to integrate this functionality into my C++ application which has other functionalities also which work independently..
so if you can guide me to get it compiled separately.. that is what I'm looking for..

Thanks in advance for prompt reply

**Comment by digikar99** [comment]
@nirajrussspacetech , did you figure it out?

**Comment by nirajrussspacetech** [comment]
yes long back.. 
I had to fork individual Makefiles of individual modules from your source code
