### ISSUE TITLE
possible cmake issue

### ISSUE THREAD

**Issue by silviucpp** [chronoxor/CppServer#3]
I think the fact that `include(SetCompilerWarnings)` it's missing in the main CMakeLists it's a mistake. 
If you add it anyway the project is not compiling because of several issues like:

```c++
cppserver/source/server/asio/ssl_client.cpp:35:11: error: field '_sending' will be initialized after field '_recive_buffer' [-Werror,-Wreorder]
          _sending(false),
          ^
cppserver/source/server/asio/ssl_client.cpp:61:11: error: field '_sending' will be initialized after field '_recive_buffer' [-Werror,-Wreorder]
          _sending(false),
          ^
```

**Comment by chronoxor** [comment]
Fixed

**Comment by chronoxor** [comment]
I temporary remove include(SetCompilerWarnings) from the project because lots of warnings in pedantic mode in third party projects (nanomsg, Restbed). Soon I'll find a way to get rid of them.
