### ISSUE TITLE
build with vs2017

### ISSUE THREAD

**Issue by ccxxbb** [chronoxor/CppServer#49]
environment:  vs2017 cmake3.19  win10
cmake output error:
-- The System identification is Windows 10.0.18363 Platform/Windows
Found OpenSSL: D:fegateway/CppServer/modules/OpenSSL/VSbbcrypto.lib (found version "1.1.1g")  
Could NOT find Crypt (missing: CRYPT_LIBRARY CRYPT_INCLUDE_DIR) 
Could NOT find WinSock (missing: WINSOCK_LIBRARY WINSOCK2_LIBRARY WINSOCK_INCLUDE_DIR) 
Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
CMake Error at modules/CppBenchmark/CMakeLists.txt:24 (include):
  include could not find load file:

    SetCompilerFeatures

CMake Error at modules/CppBenchmark/CMakeLists.txt:25 (include):
  include could not find load file:

    SetCompilerWarnings

CMake Error at modules/CppBenchmark/CMakeLists.txt:26 (include):
  include could not find load file:

    SetPlatformFeatures

CMake Error at C:/Program Files/CMake/cmake-3.19/Modules/SystemInformation.cmake:16 (file):
  file failed to open for writing (No such file or directory):

    D:fegateway/CppServer/modules/CppBenchmark/
Call Stack (most recent call first):
  modules/CppBenchmark/CMakeLists.txt:27 (include)

CMake Error at C:/Program Files/CMake/cmake-3.19/Modules/SystemInformation.cmake:18 (file):
  file failed to open for writing (No such file or directory):

    D:fegateway/CppServer/modules/CppBenchmark/
Call Stack (most recent call first):
  modules/CppBenchmark/CMakeLists.txt:27 (include)

CMake Error at C:/Program Files/CMake/cmake-3.19/Modules/SystemInformation.cmake:20 (file):
  file failed to open for writing (No such file or directory):

    D:fegateway/CppServer/modules/CppBenchmark/
Call Stack (most recent call first):
  modules/CppBenchmark/CMakeLists.txt:27 (include)

CMake Error at C:/Program Files/CMake/cmake-3.19/Modules/SystemInformation.cmake:24 (file):
  file failed to open for writing (No such file or directory):

    D:fegateway/CppServer/modules/CppBenchmark/
Call Stack (most recent call first):
  modules/CppBenchmark/CMakeLists.txt:27 (include)

CMake Error at C:/Program Files/CMake/cmake-3.19/Modules/SystemInformation.cmake:24 (file):
  file failed to open for writing (No such file or directory):

    D:fegateway/CppServer/modules/CppBenchmark/
Call Stack (most recent call first):
  modules/CppBenchmark/CMakeLists.txt:27 (include)
.........
.........

**Comment by chronoxor** [comment]
We don't support VS2017 anymore(
