### ISSUE TITLE
Server issue

### ISSUE THREAD

**Issue by randydom** [chronoxor/CppServer#5]
I noticed an issue in the server ; when disconnect all sessions or an X connected session .

Try to disable the auto-reconnection from all clients : 

        // Wait for a while...
        CppCommon::Thread::Sleep(1000);

        // Try to connect again
        Connect();

When all connected sessions are disconnected from the server try to launch a new client you’ll notice that the server will not accept any new connection .

**Comment by chronoxor** [comment]
I tried to follow your steps and replace server restart with disconnect all in tcp_chat_server.cpp

```c++
        // Disconnect all sessions
        if (line == "!")
        {
            std::cout << "Disconnecting all sessions...";
            server->DisconnectAll();
            std::cout << "Done!" << std::endl;
            continue;
        }
```

Add commented out clinet reconnect code.

As the result after I enter '!' the server drops all connected clients and they do not reconnects (right behavior), but all other clients successfully connects to the server. Tested in Windows environment.
