### ISSUE TITLE
How to connect to a wss:// URL ?

### ISSUE THREAD

**Issue by whyCPPgofast** [chronoxor/CppServer#55]
Hi,
Your library looks very clean. How do I connect a ws client to a wss:// url? In examples I only see IP address. Do I have to create my own DNS resolver?

**Comment by chronoxor** [comment]
If you need to connect over DNS please create an instance of TCPResolver and call `ConnectAsync(resolver)` method and pass it as a parameter:
```
auto resolver = std::make_shared<Asio::TCPResolver>(service());
client.ConnectAsync(resolver);
```

In this case DNS resolver will be used to resolve address into server IP.

**Comment by whyCPPgofast** [comment]
Amazing, thank you
