### ISSUE TITLE
openssl 

### ISSUE THREAD

**Issue by e71828** [chronoxor/CppServer#57]
-- The System identification is Linux 5.4.0-1015-raspi Platform/Linux
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
  OPENSSL_INCLUDE_DIR)

a probable solution: `sudo apt install libssl-dev`

**Comment by chronoxor** [comment]
Yes, required linux packages are listed in Requirements section:
![image](https://user-images.githubusercontent.com/4397805/116582277-dce3e280-a91d-11eb-9f70-f515ddac22a0.png)
