### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by toma3757** [chronoxor/CppServer#6]
Hi!

I got an error during compiling CppServer, I'm not so familiar with cmake so I can't get to work.
Here is the error:
`-- Could NOT find LIBUUID (missing: LIBUUID_LIBRARY LIBUUID_INCLUDE_DIR) 
-- Could NOT find LIBVLD (missing: LIBVLD_LIBRARY) `

`CppServer/modules/CppCommon/source/system/uuid.cpp:12:10: fatal error: uuid/uuid.h: no such file or directory
 #include <uuid/uuid.h>
          ^~~~~~~~~~~~~
compilation terminated.
modules/CppCommon/CMakeFiles/cppcommon.dir/build.make:758: recipe for target 'modules/CppCommon/CMakeFiles/cppcommon.dir/source/system/uuid.cpp.o' failed
make[2]: *** [modules/CppCommon/CMakeFiles/cppcommon.dir/source/system/uuid.cpp.o] Error 1
CMakeFiles/Makefile2:1378: recipe for target 'modules/CppCommon/CMakeFiles/cppcommon.dir/all' failed
make[1]: *** [modules/CppCommon/CMakeFiles/cppcommon.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
`

Can I get a little help?
Thanks!

**Comment by chronoxor** [comment]
What is your environment and compiler?

**Comment by chronoxor** [comment]
sudo apt-get install uuid-dev

**Comment by toma3757** [comment]
Omg... I had installed uuid package but not the dev version.
Sorry for the issue and thank you!
I built it succesfully.
