### ISSUE TITLE
Compiling error on Ubuntu 16.04

### ISSUE THREAD

**Issue by autosec-lge** [chronoxor/CppServer#7]
Dear chronoxor,

When I try to build CppServer on Ubuntu 16.04, it got an error below.
Could you know the environment and compiler to build it?

Thanks!

---------------------------------------------------------------------------------------------------------------------
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- The System identification is Linux-4.15.0-50-generic Linux 4.15.0-50-generic Platform/Linux
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.a;/usr/lib/x86_64-linux-gnu/libcrypto.a (found version "1.0.2g") 
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- The System identification is Linux-4.15.0-50-generic Linux 4.15.0-50-generic Platform/Linux
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of off64_t
-- Check size of off64_t - done
-- Looking for fseeko
-- Looking for fseeko - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- The System identification is Linux-4.15.0-50-generic Linux 4.15.0-50-generic Platform/Linux
-- Found LIBBFD: /usr/lib/x86_64-linux-gnu/libbfd.so  
-- Found LIBDL: /usr/lib/x86_64-linux-gnu/libdl.so  
-- Found LIBRT: /usr/lib/x86_64-linux-gnu/librt.so  
-- Found LIBUUID: /usr/lib/x86_64-linux-gnu/libuuid.so  
-- Could NOT find LIBVLD (missing:  LIBVLD_LIBRARY) 
-- Configuring done
CMake Error at CMakeLists.txt:95 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:95 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:95 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:80 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:80 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:95 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:95 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:80 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:95 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:80 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:95 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:80 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:80 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:80 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:80 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:80 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:95 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:62 (add_library):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:80 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:80 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:80 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:80 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:80 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:80 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:95 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:95 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:95 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:95 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:80 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:95 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:95 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:107 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:95 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:80 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:95 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:95 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:80 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:95 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:95 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:95 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:95 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:95 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:95 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at CMakeLists.txt:95 (add_executable):
  CXX_STANDARD is set to invalid value '17'

CMake Error at modules/asio.cmake:5 (add_library):
  CXX_STANDARD is set to invalid value '17'
Call Stack (most recent call first):
  modules/CMakeLists.txt:1 (include)

CMake Error at modules/cpp-optparse.cmake:11 (add_library):
  CXX_STANDARD is set to invalid value '17'
Call Stack (most recent call first):
  modules/CMakeLists.txt:3 (include)

CMake Error at modules/CppBenchmark/CMakeLists.txt:46 (add_library):
  CXX_STANDARD is set to invalid value '17'

CMake Error at modules/CppCommon/CMakeLists.txt:70 (add_library):
  CXX_STANDARD is set to invalid value '17'

CMake Error at modules/CppCommon/modules/fmt.cmake:5 (add_library):
  CXX_STANDARD is set to invalid value '17'
Call Stack (most recent call first):
  modules/CppCommon/modules/CMakeLists.txt:3 (include)

-- Generating done

**Comment by chronoxor** [comment]
GCC 5.4.0 is very old and will not be supported. Please update to the one of the latest gcc compliler which supports C++17.

**Comment by chronoxor** [comment]
Also update cmake up to 3.8 or higher to fix:
`
CMake Error at CMakeLists.txt:95 (add_executable):
CXX_STANDARD is set to invalid value '17'
`

C++ 17 is supported by CMake starts at 3.8
