### ISSUE TITLE
Get client IP

### ISSUE THREAD

**Issue by Chrys4lisfag** [chronoxor/CppServer#8]
Is there any build in method how can I get IP of a user when he connects to my tcp server?

Есть ли какой-то метод, чтобы получать ИП клиент на момент его коннекта(TCP server)?

**Comment by chronoxor** [comment]
In TCPSession/SSLSession you can use:
* socket().remote_endpoint().address().to_string() - to get the client IP address
* socket().remote_endpoint().port() - to get the client port
